import './payroll.js';

const invoke=globalThis.__TAURI__?.core?.invoke;
let lastPage=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const session=()=>JSON.parse(sessionStorage.getItem('natra.session.v1')||'{}');
const role=()=>document.querySelector('.role-pill')?.textContent?.trim()||'';
function isAdmin(){const r=role().toLowerCase();return r.includes('hr_admin')||r.includes('hr admin')}
function isEmployee(){const r=role().toLowerCase();return r.includes('employee')&&!isAdmin()}
const year=()=>new Date().getFullYear();
async function call(name,args={}){if(!invoke)throw new Error('Native application required');return await invoke(name,args)}
async function loadRows(){return await call('leave_list',{status:null})}
async function loadTypes(){return await call('leave_types_list',{})}
async function loadEmployees(){return await call('employees_list',{})}
async function loadBalances(employeeId=null){return await call('leave_balances_list',{employeeId,year:year()})}
function render(rows){const page=document.querySelector('#page');if(!page)return;const admin=isAdmin();page.innerHTML=`<section class="content"><div class="welcome"><div><span class="badge">${admin?'HR ADMIN':'EMPLOYEE'}</span><h2>${admin?'Leave Management':'My Leave'}</h2><p>${admin?'Manage leave requests, types and annual balances.':'Submit and track your leave requests and available balances.'}</p></div>${!admin?'<button class="primary" id="newLeave">+ Request leave</button>':''}</div>${admin?adminSetup(rows):employeeSummary(rows)}<div class="panel"><div class="panel-head"><div><span class="eyebrow">WORKFORCE</span><h3>${admin?'Pending and recent requests':'Your requests'}</h3></div><button id="refreshLeave">Refresh</button></div><div id="leaveRows">${rows.length?rows.map(r=>row(r,admin)).join(''):'<div class="empty">No leave requests found.</div>'}</div></div></section>`;document.querySelector('#newLeave')?.addEventListener('click',form);document.querySelector('#refreshLeave')?.addEventListener('click',loadPage);document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>review(b.dataset.review,b.dataset.status));if(admin)bindAdmin();}
function row(r,admin){const actions=admin&&r.status==='pending'?`<button class="primary" data-review="${esc(r.id)}" data-status="approved">Approve</button><button data-review="${esc(r.id)}" data-status="rejected">Reject</button>`:'';return `<div class="action"><span class="dot"></span><div><strong>${esc(r.leave_type)}</strong><small>${esc(r.start_date)} → ${esc(r.end_date)} · Employee ${esc(r.employee_id)}</small>${r.reason?`<small>${esc(r.reason)}</small>`:''}${r.reviewed_by?`<small>Reviewed by ${esc(r.reviewed_by)}</small>`:''}</div><span class="status ${r.status==='approved'?'present':r.status==='rejected'?'warn':'neutral'}">${esc(r.status)}</span>${actions}</div>`}
function adminSetup(){return `<div class="panel"><div class="panel-head"><div><span class="eyebrow">SETUP</span><h3>Leave types</h3><small>Annual allowance is the default for new employee balances.</small></div></div><div id="leaveTypes">Loading…</div><div class="form-grid" style="margin-top:14px"><label>Name<input id="typeName" placeholder="e.g. Maternity"></label><label>Annual days<input id="typeDays" type="number" min="0" value="0"></label><label>Active<select id="typeActive"><option value="1">Active</option><option value="0">Inactive</option></select></label></div><input id="typeId" type="hidden"><div id="typeMsg"></div><button class="primary green-btn" id="saveType">Save leave type</button></div><div class="panel"><div class="panel-head"><div><span class="eyebrow">BALANCES</span><h3>Employee annual balances</h3><small>Set the yearly allowance before approving leave.</small></div></div><div class="form-grid"><label>Employee<select id="balanceEmployee"></select></label><label>Leave type<select id="balanceType"></select></label><label>Year<input id="balanceYear" type="number" value="${year()}" min="2000" max="2100"></label><label>Allocated days<input id="balanceAllocated" type="number" min="0" value="0"></label><label>Used days<input id="balanceUsed" type="number" min="0" value="0"></label></div><div id="balanceMsg"></div><button class="primary green-btn" id="saveBalance">Save balance</button><div id="balanceRows" style="margin-top:14px">Loading…</div></div>`}
function employeeSummary(){return `<div class="panel"><div class="panel-head"><div><span class="eyebrow">BALANCE</span><h3>${year()} leave balance</h3></div></div><div id="myBalances">Loading…</div></div>`}
function employeeLabel(e){const full=[e.first_name,e.last_name].filter(Boolean).join(' ');return `${full||e.employee_number||e.id} · ${e.employee_number||e.id}`}
async function bindAdmin(){try{const [types,employees,balances]=await Promise.all([loadTypes(),loadEmployees(),loadBalances()]);renderTypes(types);const es=document.querySelector('#balanceEmployee');es.innerHTML=employees.filter(e=>String(e.status||'').toLowerCase()==='active').map(e=>`<option value="${esc(e.id)}">${esc(employeeLabel(e))}</option>`).join('');document.querySelector('#balanceYear').onchange=refreshBalances;document.querySelector('#balanceEmployee').onchange=refreshBalances;renderBalanceTypes(types);renderBalances(balances,types);document.querySelector('#saveType').onclick=saveType;document.querySelector('#saveBalance').onclick=saveBalance;document.querySelectorAll('[data-edit-type]').forEach(b=>b.onclick=()=>editType(types.find(t=>t.id===b.dataset.editType)));}catch(e){const m=document.querySelector('#typeMsg');if(m)m.innerHTML=`<p class="login-error">${esc(e)}</p>`}}
function renderTypes(types){const el=document.querySelector('#leaveTypes');if(!el)return;el.innerHTML=types.length?types.map(t=>`<div class="action"><div><strong>${esc(t.name)}</strong><small>${t.annual_days} day(s) / year</small></div><span class="status ${t.active?'present':'neutral'}">${t.active?'Active':'Inactive'}</span><button data-edit-type="${esc(t.id)}">Edit</button></div>`).join(''):'<div class="empty">No leave types.</div>';}
function renderBalanceTypes(types){const el=document.querySelector('#balanceType');if(!el)return;el.innerHTML=types.filter(t=>t.active).map(t=>`<option value="${esc(t.id)}">${esc(t.name)} (${t.annual_days} default)</option>`).join('');}
function renderBalances(rows,types=[]){const el=document.querySelector('#balanceRows');if(!el)return;el.innerHTML=rows.length?rows.map(r=>{const t=types.find(x=>x.id===r.leave_type_id);return `<div class="action"><div><strong>${esc(t?.name||r.leave_type_id)}</strong><small>${esc(r.year)} · Allocated ${r.allocated_days} · Used ${r.used_days}</small></div><span class="status ${r.remaining_days>0?'present':'neutral'}">${r.remaining_days} remaining</span></div>`}).join(''):'<div class="empty">No balances configured for this selection.</div>';}
async function refreshBalances(){try{const id=document.querySelector('#balanceEmployee').value;const y=Number(document.querySelector('#balanceYear').value)||year();const rows=await call('leave_balances_list',{employeeId:id||null,year:y});const types=await loadTypes();renderBalances(rows,types)}catch(e){const m=document.querySelector('#balanceMsg');if(m)m.innerHTML=`<p class="login-error">${esc(e)}</p>`}}
function editType(t){if(!t)return;document.querySelector('#typeId').value=t.id;document.querySelector('#typeName').value=t.name;document.querySelector('#typeDays').value=t.annual_days;document.querySelector('#typeActive').value=t.active?'1':'0';window.scrollTo({top:0,behavior:'smooth'})}
async function saveType(){const msg=document.querySelector('#typeMsg');try{const id=document.querySelector('#typeId').value||crypto.randomUUID();await call('leave_type_save',{request:{id,name:document.querySelector('#typeName').value.trim(),annualDays:Number(document.querySelector('#typeDays').value)||0,active:document.querySelector('#typeActive').value==='1'}});msg.innerHTML='<p class="token-note">Leave type saved.</p>';document.querySelector('#typeId').value='';document.querySelector('#typeName').value='';const types=await loadTypes();renderTypes(types);renderBalanceTypes(types);document.querySelectorAll('[data-edit-type]').forEach(b=>b.onclick=()=>editType(types.find(t=>t.id===b.dataset.editType)));}catch(e){msg.innerHTML=`<p class="login-error">${esc(e)}</p>`}}
async function saveBalance(){const msg=document.querySelector('#balanceMsg');try{const employeeId=document.querySelector('#balanceEmployee').value;const leaveTypeId=document.querySelector('#balanceType').value;const y=Number(document.querySelector('#balanceYear').value)||year();const allocated=Number(document.querySelector('#balanceAllocated').value)||0;const used=Number(document.querySelector('#balanceUsed').value)||0;if(!employeeId||!leaveTypeId)throw new Error('Select an employee and active leave type.');if(used>allocated)throw new Error('Used days cannot exceed allocated days.');await call('leave_balance_save',{request:{id:crypto.randomUUID(),employeeId,leaveTypeId,year:y,allocatedDays:allocated,usedDays:used}});msg.innerHTML='<p class="token-note">Balance saved.</p>';await refreshBalances();}catch(e){msg.innerHTML=`<p class="login-error">${esc(e)}</p>`}}
async function form(){const page=document.querySelector('#page');let types=[];try{types=await loadTypes()}catch{}page.innerHTML=`<section class="content"><div class="page-heading"><div><span class="eyebrow">EMPLOYEE</span><h2>Request leave</h2><p>Your request is saved locally and synchronized when connected.</p></div></div><div class="panel"><div class="form-grid"><label>Leave type<select id="leaveType">${types.filter(t=>t.active).map(t=>`<option value="${esc(t.name)}">${esc(t.name)}</option>`).join('')}</select></label><label>Start date<input id="leaveStart" type="date" required></label><label>End date<input id="leaveEnd" type="date" required></label><label>Reason<textarea id="leaveReason" rows="4"></textarea></label></div><div id="leaveMsg"></div><button class="primary green-btn" id="submitLeave">Submit request</button><button id="cancelLeave" style="margin-left:8px">Cancel</button></div></section>`;document.querySelector('#submitLeave').onclick=submit;document.querySelector('#cancelLeave').onclick=loadPage;if(!types.some(t=>t.active))document.querySelector('#leaveMsg').innerHTML='<p class="login-error">No active leave type is configured. Ask HR Admin to configure one.</p>'}
async function submit(){const start=document.querySelector('#leaveStart').value,end=document.querySelector('#leaveEnd').value;if(!start||!end||end<start){document.querySelector('#leaveMsg').innerHTML='<p class="login-error">Please select a valid date range.</p>';return}const user=session();const leave={id:crypto.randomUUID(),employee_id:user.employeeId||user.employee_id||'',leave_type:document.querySelector('#leaveType').value,start_date:start,end_date:end,reason:document.querySelector('#leaveReason').value.trim()||null,status:'pending',reviewed_by:null,reviewed_at:null};if(!leave.employee_id){document.querySelector('#leaveMsg').innerHTML='<p class="login-error">Employee account is not linked to an employee record.</p>';return}try{await call('leave_create',{leave});document.querySelector('#leaveMsg').innerHTML='<p class="token-note">Leave request submitted.</p>';setTimeout(loadPage,350)}catch(e){document.querySelector('#leaveMsg').innerHTML=`<p class="login-error">${esc(e)}</p>`}}
async function review(id,status){try{const user=session();await call('leave_review',{id,status,reviewed_by:user.id||user.username||'hr_admin'});loadPage()}catch(e){alert(String(e))}}
async function loadPage(){try{const rows=await loadRows();const user=session();const filtered=isEmployee()?rows.filter(r=>r.employee_id===(user.employeeId||user.employee_id)):rows;render(filtered);if(isEmployee()){const b=await loadBalances(user.employeeId||user.employee_id);const el=document.querySelector('#myBalances');el.innerHTML=b.length?b.map(r=>`<div class="action"><div><strong>${esc(r.leave_type_id)}</strong><small>${esc(r.year)} · Allocated ${r.allocated_days} · Used ${r.used_days}</small></div><span class="status ${r.remaining_days>0?'present':'neutral'}">${r.remaining_days} remaining</span></div>`).join(''):'<div class="empty">No leave balance has been configured yet.</div>';}}catch(e){const page=document.querySelector('#page');if(page)page.innerHTML=`<section class="content"><div class="panel"><p class="login-error">${esc(e)}</p></div></section>`}}
function active(){return document.querySelector('.nav-item.active')?.dataset.page==='Leave'||document.querySelector('.main h1')?.textContent?.trim()==='Leave'}
const observer=new MutationObserver(()=>{if(active()&&lastPage!==document.querySelector('#page')){lastPage=document.querySelector('#page');loadPage()}});observer.observe(document.body,{childList:true,subtree:true});
