const invoke=globalThis.__TAURI__?.core?.invoke;
let lastPage=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const role=()=>document.querySelector('.role-pill')?.textContent?.trim()||'';
function isAdmin(){const r=role().toLowerCase();return r.includes('hr_admin')||r.includes('hr admin')}
function isEmployee(){const r=role().toLowerCase();return r.includes('employee')&&!isAdmin()}
async function load(){if(!invoke)return[];return await invoke('leave_list',{status:null})}
function render(rows){const page=document.querySelector('#page');if(!page)return;const admin=isAdmin();page.innerHTML=`<section class="content"><div class="welcome"><div><span class="badge">${admin?'HR ADMIN':'EMPLOYEE'}</span><h2>${admin?'Leave Requests':'My Leave'}</h2><p>${admin?'Review and approve employee leave requests.':'Submit and track your leave requests.'}</p></div>${!admin?'<button class="primary" id="newLeave">+ Request leave</button>':''}</div><div class="panel"><div class="panel-head"><div><span class="eyebrow">WORKFORCE</span><h3>${admin?'Pending and recent requests':'Your requests'}</h3></div></div><div id="leaveRows">${rows.length?rows.map(r=>row(r,admin)).join(''):'<div class="empty">No leave requests found.</div>'}</div></div></section>`;document.querySelector('#newLeave')?.addEventListener('click',form);document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>review(b.dataset.review,b.dataset.status));}
function row(r,admin){const actions=admin&&r.status==='pending'?`<button class="primary" data-review="${esc(r.id)}" data-status="approved">Approve</button><button data-review="${esc(r.id)}" data-status="rejected">Reject</button>`:'';return `<div class="action"><span class="dot"></span><div><strong>${esc(r.leave_type)}</strong><small>${esc(r.start_date)} → ${esc(r.end_date)} · Employee ${esc(r.employee_id)}</small>${r.reason?`<small>${esc(r.reason)}</small>`:''}</div><span class="status ${r.status==='approved'?'present':r.status==='rejected'?'warn':'neutral'}">${esc(r.status)}</span>${actions}</div>`}
function form(){const page=document.querySelector('#page');page.innerHTML=`<section class="content"><div class="page-heading"><div><span class="eyebrow">EMPLOYEE</span><h2>Request leave</h2><p>Your request is saved locally and synchronized when connected.</p></div></div><div class="panel"><div class="form-grid"><label>Leave type<select id="leaveType"><option>Annual</option><option>Sick</option><option>Emergency</option><option>Unpaid</option></select></label><label>Start date<input id="leaveStart" type="date" required></label><label>End date<input id="leaveEnd" type="date" required></label><label>Reason<textarea id="leaveReason" rows="4"></textarea></label></div><div id="leaveMsg"></div><button class="primary green-btn" id="submitLeave">Submit request</button></div></section>`;document.querySelector('#submitLeave').onclick=submit}
async function submit(){const start=document.querySelector('#leaveStart').value,end=document.querySelector('#leaveEnd').value;if(!start||!end||end<start){document.querySelector('#leaveMsg').innerHTML='<p class="login-error">Please select a valid date range.</p>';return}const user=JSON.parse(sessionStorage.getItem('natra.session')||'{}');const leave={id:crypto.randomUUID(),employee_id:user.employeeId||user.employee_id||'',leave_type:document.querySelector('#leaveType').value,start_date:start,end_date:end,reason:document.querySelector('#leaveReason').value.trim()||null,status:'pending',reviewed_by:null,reviewed_at:null};if(!leave.employee_id){document.querySelector('#leaveMsg').innerHTML='<p class="login-error">Employee account is not linked to an employee record.</p>';return}try{if(!invoke)throw new Error('Native application required');await invoke('leave_create',{leave});document.querySelector('#leaveMsg').innerHTML='<p class="token-note">Leave request submitted.</p>';setTimeout(loadPage,350)}catch(e){document.querySelector('#leaveMsg').innerHTML=`<p class="login-error">${esc(e)}</p>`}}
async function review(id,status){try{const user=JSON.parse(sessionStorage.getItem('natra.session')||'{}');await invoke('leave_review',{id,status,reviewedBy:user.id||user.username||'hr_admin'});loadPage()}catch(e){alert(String(e))}}
async function loadPage(){const rows=await load();const user=JSON.parse(sessionStorage.getItem('natra.session')||'{}');const filtered=isEmployee()?rows.filter(r=>r.employee_id===(user.employeeId||user.employee_id)):rows;render(filtered)}
function active(){return document.querySelector('.nav-item.active')?.dataset.page==='Leave'||document.querySelector('.main h1')?.textContent?.trim()==='Leave'}
const observer=new MutationObserver(()=>{if(active()&&lastPage!==document.querySelector('#page')){lastPage=document.querySelector('#page');loadPage()}});observer.observe(document.body,{childList:true,subtree:true});
