const invoke=globalThis.__TAURI__?.core?.invoke;
let lastPage=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const role=()=>document.querySelector('.role-pill')?.textContent?.trim()||'';
const admin=()=>role().toLowerCase().includes('hr admin')||role().toLowerCase().includes('hr_admin');
const session=()=>{try{return JSON.parse(sessionStorage.getItem('natra.session.v1')||'{}')}catch{return{}}};
async function employees(){return invoke?await invoke('employees_list'):[]}
async function salaries(period=null){return invoke?await invoke('payroll_list',{payPeriod:period}):[]}
async function periods(){return invoke?await invoke('payroll_periods'):[]}
function money(v){return Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
async function render(){const page=document.querySelector('#page');if(!page)return;const user=session();const rows=await salaries();const visible=admin()?rows:rows.filter(r=>r.employee_id===(user.employeeId||user.employee_id));const ps=admin()?await periods():[];page.innerHTML=`<section class="content"><div class="welcome"><div><span class="badge">${admin()?'HR ADMIN':'EMPLOYEE'}</span><h2>${admin()?'Payroll':'My Payroll'}</h2><p>${admin()?'Create, review and lock employee payroll periods.':'View your salary records stored securely in the ERP.'}</p></div>${admin()?'<button class="primary green-btn" id="newPayroll">+ Add salary</button>':''}</div>${admin()?`<div class="panel"><div class="panel-head"><div><span class="eyebrow">PAYROLL PERIODS</span><h3>Period control</h3></div></div><div id="periodRows">${ps.length?ps.map(periodRow).join(''):'<div class="empty">No payroll periods yet. Add a salary record to create one.</div>'}</div></div>`:''}<div class="panel"><div class="panel-head"><div><span class="eyebrow">SALARY RECORDS</span><h3>${admin()?'Payroll register':'Salary history'}</h3></div><span class="status present">Offline-ready</span></div><div id="payrollRows">${visible.length?visible.map(row).join(''):'<div class="empty">No payroll records found.</div>'}</div></div><div id="payrollForm"></div><p id="payrollActionMsg"></p></section>`;document.querySelector('#newPayroll')?.addEventListener('click',showForm);document.querySelectorAll('[data-process-period]').forEach(b=>b.addEventListener('click',()=>processPeriod(b.dataset.processPeriod)))}
function periodRow(p){return `<div class="action"><span class="dot"></span><div><strong>${esc(p.period)}</strong><small>${p.processed_by?`Processed by ${esc(p.processed_by)}`:'Draft period'}</small></div><span class="status ${p.status==='locked'?'present':'neutral'}">${esc(p.status)}</span>${p.status!=='locked'?`<button class="primary green-btn" data-process-period="${esc(p.period)}">Process & lock</button>`:''}</div>`}
function row(r){return `<div class="action"><span class="dot"></span><div><strong>${esc(r.pay_period)}</strong><small>Employee ${esc(r.employee_id)} · Base ${money(r.base_salary)} · Allowances ${money(r.allowances)} · Deductions ${money(r.deductions)}</small></div><strong>${money(r.net_salary)}</strong><span class="status ${r.status==='processed'?'present':'neutral'}">${esc(r.status)}</span></div>`}
async function showForm(){const box=document.querySelector('#payrollForm');const list=await employees();box.innerHTML=`<div class="panel" style="margin-top:16px"><div class="panel-head"><div><span class="eyebrow">NEW PAYROLL</span><h3>Create salary record</h3></div></div><div class="form-grid"><label>Employee<select id="salaryEmployee">${list.filter(e=>String(e.status).toLowerCase()==='active').map(e=>`<option value="${esc(e.id)}">${esc(e.employee_number)} — ${esc(e.first_name)} ${esc(e.last_name)}</option>`).join('')}</select></label><label>Pay period<input id="salaryPeriod" type="month" required></label><label>Base salary<input id="salaryBase" type="number" min="0" step="0.01" value="0"></label><label>Allowances<input id="salaryAllowances" type="number" min="0" step="0.01" value="0"></label><label>Deductions<input id="salaryDeductions" type="number" min="0" step="0.01" value="0"></label></div><p id="payrollMsg"></p><button class="primary green-btn" id="savePayroll">Save salary</button></div>`;document.querySelector('#savePayroll').onclick=save}
async function save(){const base=Number(document.querySelector('#salaryBase').value)||0,allowances=Number(document.querySelector('#salaryAllowances').value)||0,deductions=Number(document.querySelector('#salaryDeductions').value)||0,period=document.querySelector('#salaryPeriod').value;const msg=document.querySelector('#payrollMsg');if(!period){msg.innerHTML='<p class="login-error">Select a pay period.</p>';return}if(deductions>base+allowances){msg.innerHTML='<p class="login-error">Deductions cannot exceed gross salary.</p>';return}const employee=document.querySelector('#salaryEmployee')?.value;if(!employee){msg.innerHTML='<p class="login-error">No active employee is available.</p>';return}const salary={id:crypto.randomUUID(),employee_id:employee,pay_period:period,base_salary:base,allowances,deductions,net_salary:base+allowances-deductions,status:'draft'};try{await invoke('payroll_create',{salary});msg.innerHTML='<p class="token-note">Salary record saved locally and queued for synchronization.</p>';setTimeout(render,350)}catch(e){msg.innerHTML=`<p class="login-error">${esc(e)}</p>`}}
async function processPeriod(period){if(!confirm(`Process and lock payroll period ${period}? This will prevent further edits.`))return;const user=session();const by=user.username||'HR Admin';const msg=document.querySelector('#payrollActionMsg');try{await invoke('payroll_process',{period,processedBy:by});msg.innerHTML='<p class="token-note">Payroll processed and period locked successfully.</p>';setTimeout(render,350)}catch(e){msg.innerHTML=`<p class="login-error">${esc(e)}</p>`}}
function active(){return document.querySelector('.nav-item.active')?.dataset.page==='Payroll'||document.querySelector('.main h1')?.textContent?.trim()==='Payroll'}
window.addEventListener('natra:page',e=>{if(e.detail?.page==='Payroll'&&active())render()});
