const invoke=globalThis.__TAURI__?.core?.invoke;
let lastPage=null;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const role=()=>document.querySelector('.role-pill')?.textContent?.trim()||'';
const admin=()=>role().toLowerCase().includes('hr admin')||role().toLowerCase().includes('hr_admin');
const session=()=>{try{return JSON.parse(sessionStorage.getItem('natra.session.v1')||'{}')}catch{return{}}};
async function employees(){return invoke?await invoke('employees_list'):[]}
async function salaries(period=null){return invoke?await invoke('payroll_list',{payPeriod:period}):[]}
function money(v){return Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}
async function render(){const page=document.querySelector('#page');if(!page)return;const user=session();const rows=await salaries();const visible=admin()?rows:rows.filter(r=>r.employee_id===(user.employeeId||user.employee_id));page.innerHTML=`<section class="content"><div class="welcome"><div><span class="badge">${admin()?'HR ADMIN':'EMPLOYEE'}</span><h2>${admin()?'Payroll':'My Payroll'}</h2><p>${admin()?'Create, review and manage employee salary records.':'View your salary records stored securely in the ERP.'}</p></div>${admin()?'<button class="primary green-btn" id="newPayroll">+ Add salary</button>':''}</div><div class="panel"><div class="panel-head"><div><span class="eyebrow">SALARY RECORDS</span><h3>${admin()?'Payroll register':'Salary history'}</h3></div><span class="status present">Offline-ready</span></div><div id="payrollRows">${visible.length?visible.map(row).join(''):'<div class="empty">No payroll records found.</div>'}</div></div><div id="payrollForm"></div></section>`;document.querySelector('#newPayroll')?.addEventListener('click',showForm)}
function row(r){return `<div class="action"><span class="dot"></span><div><strong>${esc(r.pay_period)}</strong><small>Employee ${esc(r.employee_id)} · Base ${money(r.base_salary)} · Allowances ${money(r.allowances)} · Deductions ${money(r.deductions)}</small></div><strong>${money(r.net_salary)}</strong><span class="status ${r.status==='processed'?'present':'neutral'}">${esc(r.status)}</span></div>`}
async function showForm(){const box=document.querySelector('#payrollForm');const list=await employees();box.innerHTML=`<div class="panel" style="margin-top:16px"><div class="panel-head"><div><span class="eyebrow">NEW PAYROLL</span><h3>Create salary record</h3></div></div><div class="form-grid"><label>Employee<select id="salaryEmployee">${list.map(e=>`<option value="${esc(e.id)}">${esc(e.employee_number)} — ${esc(e.first_name)} ${esc(e.last_name)}</option>`).join('')}</select></label><label>Pay period<input id="salaryPeriod" type="month" required></label><label>Base salary<input id="salaryBase" type="number" min="0" step="0.01" value="0"></label><label>Allowances<input id="salaryAllowances" type="number" min="0" step="0.01" value="0"></label><label>Deductions<input id="salaryDeductions" type="number" min="0" step="0.01" value="0"></label><label>Status<select id="salaryStatus"><option value="draft">Draft</option><option value="processed">Processed</option></select></label></div><p id="payrollMsg"></p><button class="primary green-btn" id="savePayroll">Save salary</button></div>`;document.querySelector('#savePayroll').onclick=save}
async function save(){const base=Number(document.querySelector('#salaryBase').value)||0,allowances=Number(document.querySelector('#salaryAllowances').value)||0,deductions=Number(document.querySelector('#salaryDeductions').value)||0,period=document.querySelector('#salaryPeriod').value;const msg=document.querySelector('#payrollMsg');if(!period){msg.innerHTML='<p class="login-error">Select a pay period.</p>';return}const salary={id:crypto.randomUUID(),employee_id:document.querySelector('#salaryEmployee').value,pay_period:period,base_salary:base,allowances,deductions,net_salary:Math.max(0,base+allowances-deductions),status:document.querySelector('#salaryStatus').value};try{await invoke('payroll_create',{salary});msg.innerHTML='<p class="token-note">Salary record saved locally and queued for synchronization.</p>';setTimeout(render,350)}catch(e){msg.innerHTML=`<p class="login-error">${esc(e)}</p>`}}
function active(){return document.querySelector('.nav-item.active')?.dataset.page==='Payroll'||document.querySelector('.main h1')?.textContent?.trim()==='Payroll'}
const observer=new MutationObserver(()=>{if(active()&&lastPage!==document.querySelector('#page')){lastPage=document.querySelector('#page');render()}});observer.observe(document.body,{childList:true,subtree:true});
