use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SalaryRecord { pub id:String, pub employee_id:String, pub pay_period:String, pub base_salary:f64, pub allowances:f64, pub deductions:f64, pub net_salary:f64, pub status:String }

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct PayrollPeriod { pub id:String, pub period:String, pub status:String, pub processed_at:Option<String>, pub processed_by:Option<String> }

pub fn migrate(c:&Connection)->Result<(),rusqlite::Error>{c.execute_batch("CREATE TABLE IF NOT EXISTS salary_records(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL REFERENCES employees(id),pay_period TEXT NOT NULL,base_salary REAL NOT NULL DEFAULT 0,allowances REAL NOT NULL DEFAULT 0,deductions REAL NOT NULL DEFAULT 0,net_salary REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(employee_id,pay_period)); CREATE TABLE IF NOT EXISTS payroll_periods(id TEXT PRIMARY KEY,period TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'draft',processed_at TEXT,processed_by TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE INDEX IF NOT EXISTS idx_salary_period ON salary_records(pay_period); CREATE INDEX IF NOT EXISTS idx_salary_employee ON salary_records(employee_id);")}

pub fn create(c:&mut Connection,s:&SalaryRecord,now:&str)->Result<(),rusqlite::Error>{let tx=c.transaction()?;ensure_open_period(&tx,&s.pay_period,now)?;tx.execute("INSERT INTO salary_records(id,employee_id,pay_period,base_salary,allowances,deductions,net_salary,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)",params![s.id,s.employee_id,s.pay_period,s.base_salary,s.allowances,s.deductions,s.net_salary,"draft",now,now])?;queue(&tx,s,now)?;tx.commit()}

pub fn list(c:&Connection,pay_period:Option<&str>)->Result<Vec<SalaryRecord>,rusqlite::Error>{let mut out=Vec::new();if let Some(p)=pay_period{let mut q=c.prepare("SELECT id,employee_id,pay_period,base_salary,allowances,deductions,net_salary,status FROM salary_records WHERE pay_period=? ORDER BY employee_id")?;for r in q.query_map([p],row)?{out.push(r?)}}else{let mut q=c.prepare("SELECT id,employee_id,pay_period,base_salary,allowances,deductions,net_salary,status FROM salary_records ORDER BY pay_period DESC,employee_id")?;for r in q.query_map([],row)?{out.push(r?)}}Ok(out)}

pub fn update(c:&mut Connection,s:&SalaryRecord,now:&str)->Result<(),rusqlite::Error>{let tx=c.transaction()?;let open:i64=tx.query_row("SELECT COUNT(*) FROM payroll_periods WHERE period=? AND status!='locked'",[&s.pay_period],|r|r.get(0))?;if open==0{return Err(rusqlite::Error::InvalidParameterName("payroll period is locked or missing".into()))}let n=tx.execute("UPDATE salary_records SET employee_id=?,pay_period=?,base_salary=?,allowances=?,deductions=?,net_salary=?,status=?,updated_at=? WHERE id=?",params![s.employee_id,s.pay_period,s.base_salary,s.allowances,s.deductions,s.net_salary,"draft",now,s.id])?;if n==0{return Err(rusqlite::Error::QueryReturnedNoRows)}queue(&tx,s,now)?;tx.commit()}

pub fn period(c:&Connection,p:&str)->Result<PayrollPeriod,rusqlite::Error>{c.query_row("SELECT id,period,status,processed_at,processed_by FROM payroll_periods WHERE period=?",[p],|r|Ok(PayrollPeriod{id:r.get(0)?,period:r.get(1)?,status:r.get(2)?,processed_at:r.get(3)?,processed_by:r.get(4)?}))}
pub fn process(c:&mut Connection,p:&str,by:&str,now:&str)->Result<(),rusqlite::Error>{let tx=c.transaction()?;let status:String=tx.query_row("SELECT status FROM payroll_periods WHERE period=?",[p],|r|r.get(0))?;if status=="locked"{return Err(rusqlite::Error::InvalidParameterName("payroll period is already locked".into()))}tx.execute("UPDATE salary_records SET net_salary=base_salary+allowances-deductions,status='processed',updated_at=? WHERE pay_period=? AND status='draft'",params![now,p])?;let n=tx.execute("UPDATE payroll_periods SET status='locked',processed_at=?,processed_by=?,updated_at=? WHERE period=?",params![now,by,now,p])?;if n==0{return Err(rusqlite::Error::QueryReturnedNoRows)}let mut q=tx.prepare("SELECT id,employee_id,pay_period,base_salary,allowances,deductions,net_salary,status FROM salary_records WHERE pay_period=?")?;let rows=q.query_map([p],row)?;for item in rows{queue(&tx,&item?,now)?;}tx.commit()}
pub fn ensure_open_period(c:&Connection,p:&str,now:&str)->Result<(),rusqlite::Error>{c.execute("INSERT INTO payroll_periods(id,period,status,created_at,updated_at) VALUES(?,?, 'draft',?,?) ON CONFLICT(period) DO NOTHING",params![format!("period-{}",p),p,now,now])?;Ok(())}
fn queue(tx:&rusqlite::Transaction<'_>,s:&SalaryRecord,now:&str)->Result<(),rusqlite::Error>{let payload=serde_json::to_string(s).unwrap_or_default();tx.execute("INSERT INTO sync_outbox(id,operation,entity,entity_id,payload,created_at) VALUES(?, 'upsert','salary',?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,created_at=excluded.created_at,last_error=NULL",params![format!("sync-salary-{}",s.id),s.id,payload,now])?;Ok(())}
fn row(r:&rusqlite::Row<'_>)->Result<SalaryRecord,rusqlite::Error>{Ok(SalaryRecord{id:r.get(0)?,employee_id:r.get(1)?,pay_period:r.get(2)?,base_salary:r.get(3)?,allowances:r.get(4)?,deductions:r.get(5)?,net_salary:r.get(6)?,status:r.get(7)?})}
