use rusqlite::{params, Connection};
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SalaryRecord { pub id:String,pub employee_id:String,pub pay_period:String,pub base_salary:f64,pub allowances:f64,pub deductions:f64,pub net_salary:f64,pub status:String }

pub fn migrate(c:&Connection)->Result<(),rusqlite::Error>{c.execute_batch("CREATE TABLE IF NOT EXISTS salary_records(id TEXT PRIMARY KEY,employee_id TEXT NOT NULL REFERENCES employees(id),pay_period TEXT NOT NULL,base_salary REAL NOT NULL DEFAULT 0,allowances REAL NOT NULL DEFAULT 0,deductions REAL NOT NULL DEFAULT 0,net_salary REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'draft',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(employee_id,pay_period)); CREATE INDEX IF NOT EXISTS idx_salary_period ON salary_records(pay_period); CREATE INDEX IF NOT EXISTS idx_salary_employee ON salary_records(employee_id);")}
pub fn create(c:&mut Connection,s:&SalaryRecord,now:&str)->Result<(),rusqlite::Error>{let tx=c.transaction()?;tx.execute("INSERT INTO salary_records(id,employee_id,pay_period,base_salary,allowances,deductions,net_salary,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)",params![s.id,s.employee_id,s.pay_period,s.base_salary,s.allowances,s.deductions,s.net_salary,s.status,now,now])?;queue(&tx,s,now)?;tx.commit()}
pub fn list(c:&Connection,pay_period:Option<&str>)->Result<Vec<SalaryRecord>,rusqlite::Error>{let mut out=Vec::new();if let Some(p)=pay_period{let mut q=c.prepare("SELECT id,employee_id,pay_period,base_salary,allowances,deductions,net_salary,status FROM salary_records WHERE pay_period=? ORDER BY employee_id")?;for r in q.query_map([p],row)?{out.push(r?)}}else{let mut q=c.prepare("SELECT id,employee_id,pay_period,base_salary,allowances,deductions,net_salary,status FROM salary_records ORDER BY pay_period DESC,employee_id")?;for r in q.query_map([],row)?{out.push(r?)}}Ok(out)}
pub fn update(c:&mut Connection,s:&SalaryRecord,now:&str)->Result<(),rusqlite::Error>{let tx=c.transaction()?;let n=tx.execute("UPDATE salary_records SET employee_id=?,pay_period=?,base_salary=?,allowances=?,deductions=?,net_salary=?,status=?,updated_at=? WHERE id=?",params![s.employee_id,s.pay_period,s.base_salary,s.allowances,s.deductions,s.net_salary,s.status,now,s.id])?;if n==0{return Err(rusqlite::Error::QueryReturnedNoRows)}queue(&tx,s,now)?;tx.commit()}
fn queue(tx:&rusqlite::Transaction<'_>,s:&SalaryRecord,now:&str)->Result<(),rusqlite::Error>{let payload=serde_json::to_string(s).unwrap_or_default();tx.execute("INSERT INTO sync_outbox(id,operation,entity,entity_id,payload,created_at) VALUES(?, 'upsert','salary',?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,created_at=excluded.created_at,last_error=NULL",params![format!("sync-salary-{}",s.id),s.id,payload,now])?;Ok(())}
fn row(r:&rusqlite::Row<'_>)->Result<SalaryRecord,rusqlite::Error>{Ok(SalaryRecord{id:r.get(0)?,employee_id:r.get(1)?,pay_period:r.get(2)?,base_salary:r.get(3)?,allowances:r.get(4)?,deductions:r.get(5)?,net_salary:r.get(6)?,status:r.get(7)?})}
