import './styles.css';
import { employeeModule } from './modules/employees.js';
import { createAttendanceToken } from './core/attendance.js';
import { demoEmployees } from './data/seed.js';
import { loadEmployees, saveEmployees, loadAttendance, saveAttendance } from './core/storage.js';
import { encodeAttendancePayload } from './core/qr.js';
import { setSession, getSession, clearSession, canAccess } from './core/session.js';

const invokeNative=globalThis.__TAURI__?.core?.invoke;
const nav=[['Dashboard','▦'],['Employees','◉'],['Attendance','◷'],['Leave','◫'],['Payroll','▤'],['Documents','□'],['Reports','⌁']];
const state={role:null,user:null,active:'Dashboard',employees:loadEmployees(demoEmployees),attendance:loadAttendance(),settings:loadSettings()};
function loadSettings(){try{return {...defaultSettings,...JSON.parse(localStorage.getItem('natra.hr.settings')||'{}')}}catch{return {...defaultSettings}}}
const defaultSettings={companyName:'NATRA ERP Company',attendanceWindow:60,timezone:'Africa/Addis_Ababa',allowEmployeeQr:true,requireActiveEmployee:true};
function saveSettings(){localStorage.setItem('natra.hr.settings',JSON.stringify(state.settings))}
function loginPage(error=''){document.querySelector('#app').innerHTML=`<main class="login-page"><form class="login-card" id="loginForm"><div class="brand"><div class="brand-mark">N</div><div><strong>NATRA</strong><span>ERP</span></div></div><span class="eyebrow">SECURE WORKSPACE</span><h1>Sign in</h1><p>Access your company workspace securely.</p>${error?`<div class="login-error">${escapeHtml(error)}</div>`:''}<label>Username<input name="username" autocomplete="username" required></label><label>Password<input name="password" type="password" autocomplete="current-password" required></label><button class="primary green-btn full">Sign in</button></form></main>`;document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{if(!invokeNative)throw new Error('The native application is required for secure login.');const user=await invokeNative('login',data);setSession(user);state.user=user;state.role=user.role;state.active='Dashboard';render()}catch(err){loginPage('Invalid username or password.')}}}
async function loadNativeAttendance(){if(!invokeNative)return;try{const rows=await invokeNative('attendance_today');state.attendance=rows.map(a=>({id:a.id,employeeId:a.employee_id,employeeName:a.employee_name,department:a.department||'',attendanceDate:a.attendance_date,checkInAt:a.check_in_at,tokenId:a.token_id,status:a.status}));saveAttendance(state.attendance)}catch(e){console.warn('Native attendance unavailable; using development data.',e)}}
async function render(){if(!state.role){const session=getSession();if(session){state.user=session;state.role=session.role}else{return loginPage()}}if(!canAccess(state.role,state.active))state.active='Dashboard';if(state.active==='Attendance')await loadNativeAttendance();document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">N</div><div><strong>NATRA</strong><span>ERP</span></div></div><div class="role-pill"><span></span>${escapeHtml(state.role)}</div><nav>${nav.filter(([l])=>canAccess(state.role,l)).map(([l,i])=>`<button class="nav-item ${state.active===l?'active':''}" data-page="${l}"><i>${i}</i>${l}</button>`).join('')}${state.role==='HR Admin'?'<button class="nav-item '+(state.active==='Settings'?'active':'')+'" data-page="Settings"><i>⚙</i>Settings</button>':''}</nav><div class="sidebar-bottom"><button class="nav-item" id="logout"><i>↪</i>Sign out</button></div></aside><main class="main"><header class="topbar"><div><p class="eyebrow">COMPANY OPERATIONS</p><h1>${state.active}</h1></div><div class="profile"><div class="avatar">${escapeHtml((state.user?.displayName||state.user?.username||'U').slice(0,2).toUpperCase())}</div><div><strong>${escapeHtml(state.user?.displayName||state.user?.username||'User')}</strong><small>${escapeHtml(state.role)}</small></div></div></header><div id="page"></div></main></div>`;const page=document.querySelector('#page');if(state.active==='Employees')page.append(await employeeModule(state.employees,employees=>saveEmployees(employees)));else if(state.active==='Attendance')page.innerHTML=attendancePage();else if(state.active==='Settings'&&state.role==='HR Admin')page.innerHTML=settingsPage();else page.innerHTML=dashboard();bindNavigation();document.querySelector('#logout').onclick=()=>{clearSession();state.role=null;state.user=null;state.active='Dashboard';render()};bindAttendance();bindSettings()}
function bindNavigation(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{const page=b.dataset.page;if(page==='Settings'&&state.role!=='HR Admin')return;if(page!=='Settings'&&canAccess(state.role,page)){state.active=page;render()}else if(page==='Settings'){state.active=page;render()}})}
function settingsPage(){return `<section class="content"><div class="page-heading"><div><span class="eyebrow">ADMINISTRATION</span><h2>HR Admin Settings</h2><p>Configure company and workforce rules.</p></div><button class="primary green-btn" id="saveSettings">Save settings</button></div><div class="grid-two"><div class="panel"><div class="panel-head"><div><span class="eyebrow">COMPANY</span><h3>Organization</h3></div></div><div class="form-grid"><label>Company name<input id="companyName" value="${escapeHtml(state.settings.companyName)}"></label><label>Timezone<input id="timezone" value="${escapeHtml(state.settings.timezone)}"></label></div></div><div class="panel"><div class="panel-head"><div><span class="eyebrow">ATTENDANCE</span><h3>QR policy</h3></div></div><div class="form-grid"><label>QR validity (seconds)<input id="attendanceWindow" type="number" min="15" max="300" value="${state.settings.attendanceWindow}"></label><label class="toggle-row"><input id="allowEmployeeQr" type="checkbox" ${state.settings.allowEmployeeQr?'checked':''}> Allow employees to generate QR</label><label class="toggle-row"><input id="requireActiveEmployee" type="checkbox" ${state.settings.requireActiveEmployee?'checked':''}> Require active employee status</label></div><p class="qr-help">QR policy changes apply to newly generated tokens.</p></div></div><div id="settingsStatus"></div></section>`}
function bindSettings(){if(state.active!=='Settings')return;document.querySelector('#saveSettings')?.addEventListener('click',()=>{state.settings={...state.settings,companyName:document.querySelector('#companyName').value.trim()||defaultSettings.companyName,timezone:document.querySelector('#timezone').value.trim()||defaultSettings.timezone,attendanceWindow:Math.max(15,Math.min(300,Number(document.querySelector('#attendanceWindow').value)||60)),allowEmployeeQr:document.querySelector('#allowEmployeeQr').checked,requireActiveEmployee:document.querySelector('#requireActiveEmployee').checked};saveSettings();document.querySelector('#settingsStatus').innerHTML='<p class="token-note">Settings saved successfully.</p>'})}
function dashboard(){const isEmployee=state.role==='Employee';return `<section class="content"><div class="welcome"><div><span class="badge">${isEmployee?'EMPLOYEE WORKSPACE':'LIVE WORKFORCE'}</span><h2>Good morning, ${escapeHtml(state.user?.displayName||state.user?.username||state.role)}.</h2><p>${isEmployee?'Manage your attendance, leave and documents.':'Manage your workforce from one secure workspace.'}</p></div>${isEmployee?'':'<button class="primary" id="goEmployees">+ Add employee</button>'}</div><div class="stats">${card(isEmployee?'My attendance':'Employees',isEmployee?todayCount():state.employees.filter(e=>e.status==='active').length,isEmployee?'Today':'Active workforce','Persistent','up')}${card('Present today',todayCount(),'Attendance','Check-ins','up')}${card('On leave','14','Currently away','5.6%','neutral')}${isEmployee?'':card('Pending requests','8','Needs review','3 urgent','warn')}</div><div class="grid-two"><div class="panel"><div class="panel-head"><div><span class="eyebrow">TODAY</span><h3>Attendance overview</h3></div><button data-page="Attendance">View all →</button></div><div class="progress"><div style="width:${state.employees.length?Math.min(100,todayCount()/state.employees.length*100):0}%"></div></div><div class="legend"><span>Present <b>${todayCount()}</b></span><span>Employees <b>${state.employees.length}</b></span></div></div><div class="panel"><div class="panel-head"><div><span class="eyebrow">WORKSPACE</span><h3>${isEmployee?'My tools':'Action center'}</h3></div></div><div class="action"><span class="dot"></span><div><strong>Attendance</strong><small>${isEmployee?'Generate your one-time QR':'View today’s check-ins'}</small></div><button data-page="Attendance">Open</button></div></div></div></section>`}
function attendancePage(){return `<section class="content"><div class="welcome"><div><span class="badge">${state.role==='Employee'?'EMPLOYEE SELF CHECK-IN':'ATTENDANCE'}</span><h2>One-time QR attendance</h2><p>Generate a short-lived QR tied to the signed-in employee. A phone camera can scan the QR to verify attendance.</p></div>${state.role==='Employee'&&state.settings.allowEmployeeQr?'<button class="primary" id="generateQr">Generate my QR</button>':''}</div><div class="grid-two attendance-grid"><div class="panel qr-panel" id="qrPanel"><div class="panel-head"><div><span class="eyebrow">SECURE TOKEN</span><h3>Attendance QR</h3></div><span class="status present">One-time</span></div><div class="qr-placeholder">${state.role==='Employee'?'QR':'Employee QR scan records will appear here'}</div><p class="qr-help">The QR is valid for ${state.settings.attendanceWindow} seconds and can be used once.</p><div id="qrStatus"></div></div><div class="panel"><div class="panel-head"><div><span class="eyebrow">TODAY</span><h3>Recorded check-ins</h3></div></div><div id="attendanceRows">${attendanceRows()}</div></div></div></section>`}
function attendanceRows(){const rows=state.attendance.filter(a=>a.attendanceDate===today());return rows.length?rows.map(a=>`<div class="action"><span class="dot"></span><div><strong>${escapeHtml(a.employeeName||'Employee')}</strong><small>${new Date(a.checkInAt).toLocaleTimeString()} · ${escapeHtml(a.department||'')}</small></div><span class="status present">Present</span></div>`).join(''):`<div class="empty">No check-ins recorded today.</div>`}
function bindAttendance(){document.querySelector('#goEmployees')?.addEventListener('click',()=>{state.active='Employees';render()});const gen=document.querySelector('#generateQr');if(gen)gen.onclick=()=>{const employee=state.user?.employeeId?state.employees.find(e=>e.id===state.user.employeeId):null;if(!employee)return alert('Employee record not found.');state.currentToken=createAttendanceToken(employee.id);state.currentToken.expiresAt=Date.now()+state.settings.attendanceWindow*1000;const payload=encodeAttendancePayload(state.currentToken);document.querySelector('#qrPanel').classList.add('token-ready');document.querySelector('.qr-placeholder').textContent=state.currentToken.nonce.slice(0,8).toUpperCase();document.querySelector('#qrStatus').innerHTML='<p class="token-note">QR generated. Valid for '+state.settings.attendanceWindow+' seconds. Scan it with a phone camera.</p>';state.currentPayload=payload}}
function today(){return new Date().toISOString().slice(0,10)}function todayCount(){return state.attendance.filter(a=>a.attendanceDate===today()).length}function card(a,b,c,d,t){return `<div class="stat"><span class="eyebrow">${a}</span><strong>${b}</strong><div><small>${c}</small><em class="${t}">${d}</em></div></div>`}function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
render();