import './styles.css';
import { employeeModule } from './modules/employees.js';
import { createAttendanceToken } from './core/attendance.js';
import { demoEmployees } from './data/seed.js';

const nav = [['Dashboard','▦'],['Employees','◉'],['Attendance','◷'],['Leave','◫'],['Payroll','▤'],['Documents','□'],['Reports','⌁']];
const state = { role:'HR Admin', active:'Dashboard', employees:structuredClone(demoEmployees), attendance:[] };

function render(){
 document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">N</div><div><strong>NATRA</strong><span>ERP</span></div></div><div class="role-pill"><span></span>${state.role}</div><nav>${nav.map(([l,i])=>`<button class="nav-item ${state.active===l?'active':''}" data-page="${l}"><i>${i}</i>${l}</button>`).join('')}</nav><div class="sidebar-bottom"><button class="nav-item"><i>⚙</i>Settings</button></div></aside><main class="main"><header class="topbar"><div><p class="eyebrow">COMPANY OPERATIONS</p><h1>${state.active}</h1></div><div class="profile"><div class="avatar">HA</div><div><strong>HR Admin</strong><small>Administrator</small></div><span>⌄</span></div></header><div id="page"></div></main></div>`;
 const page=document.querySelector('#page');
 if(state.active==='Employees') page.append(employeeModule(state.employees,()=>{}));
 else if(state.active==='Attendance') page.innerHTML=attendancePage();
 else page.innerHTML=dashboard();
 bindNavigation(); bindAttendance();
}
function bindNavigation(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.active=b.dataset.page;render()})}
function dashboard(){return `<section class="content"><div class="welcome"><div><span class="badge">LIVE WORKFORCE</span><h2>Good morning, HR Admin.</h2><p>Manage your workforce from one secure workspace.</p></div><button class="primary" id="goEmployees">+ Add employee</button></div><div class="stats">${card('Employees',state.employees.filter(e=>e.status==='active').length,'Active workforce','Live','up')}${card('Present today',state.attendance.length,'Attendance','Check-ins','up')}${card('On leave','14','Currently away','5.6%','neutral')}${card('Pending requests','8','Needs review','3 urgent','warn')}</div><div class="grid-two"><div class="panel"><div class="panel-head"><div><span class="eyebrow">TODAY</span><h3>Attendance overview</h3></div><button data-page="Attendance">View all →</button></div><div class="progress"><div style="width:${state.employees.length?Math.min(100,state.attendance.length/state.employees.length*100):0}%"></div></div><div class="legend"><span>Present <b>${state.attendance.length}</b></span><span>Employees <b>${state.employees.length}</b></span></div></div><div class="panel"><div class="panel-head"><div><span class="eyebrow">ACTION CENTER</span><h3>Needs your attention</h3></div></div><div class="action"><span class="dot warn-dot"></span><div><strong>8 leave requests</strong><small>Waiting for approval</small></div><button>Review</button></div><div class="action"><span class="dot"></span><div><strong>${state.employees.length} employees</strong><small>Workforce records</small></div><button data-page="Employees">Open</button></div></div></div></section>`}
function attendancePage(){return `<section class="content"><div class="welcome"><div><span class="badge">EMPLOYEE SELF CHECK-IN</span><h2>One-time QR attendance</h2><p>Generate a short-lived QR tied to the signed-in employee. The scanner records the exact date and time.</p></div><button class="primary" id="generateQr">Generate my QR</button></div><div class="grid-two attendance-grid"><div class="panel qr-panel" id="qrPanel"><div class="panel-head"><div><span class="eyebrow">SECURE TOKEN</span><h3>Attendance QR</h3></div><span class="status present">One-time</span></div><div class="qr-placeholder">QR</div><p class="qr-help">Development mode: the token is shown as text until a QR renderer is connected.</p><button class="primary green-btn full" id="scanDemo">Simulate successful scan</button><div id="qrStatus"></div></div><div class="panel"><div class="panel-head"><div><span class="eyebrow">TODAY</span><h3>Recorded check-ins</h3></div></div><div id="attendanceRows">${attendanceRows()}</div></div></div></section>`}
function attendanceRows(){return state.attendance.length?state.attendance.map(a=>`<div class="action"><span class="dot"></span><div><strong>${a.employeeName}</strong><small>${new Date(a.checkInAt).toLocaleTimeString()} · ${a.department}</small></div><span class="status present">Present</span></div>`).join(''):`<div class="empty">No check-ins recorded in this session.</div>`}
function bindAttendance(){document.querySelector('#goEmployees')?.addEventListener('click',()=>{state.active='Employees';render()});const gen=document.querySelector('#generateQr');if(gen)gen.onclick=()=>{const employee=state.employees[0];state.currentToken=createAttendanceToken(employee.id);document.querySelector('#qrPanel').classList.add('token-ready');document.querySelector('.qr-placeholder').textContent=state.currentToken.nonce.slice(0,8).toUpperCase();document.querySelector('#qrStatus').innerHTML='<p class="token-note">QR generated. Valid for 60 seconds.</p>'};document.querySelector('#scanDemo')?.addEventListener('click',()=>{if(!state.currentToken)return alert('Generate your QR first.');const employee=state.employees[0];const date=new Date().toISOString().slice(0,10);if(state.attendance.some(a=>a.employeeId===employee.id&&a.attendanceDate===date))return alert('Attendance already recorded for this employee today.');state.attendance.push({employeeId:employee.id,employeeName:`${employee.firstName} ${employee.lastName}`,department:employee.department,attendanceDate:date,checkInAt:new Date().toISOString()});state.currentToken.consumedAt=new Date().toISOString();render()})}
function card(a,b,c,d,t){return `<div class="stat"><span class="eyebrow">${a}</span><strong>${b}</strong><div><small>${c}</small><em class="${t}">${d}</em></div></div>`}
render();